local term = require("rvpm.terminal")

describe("rvpm.terminal._buffer_is_empty_scratch", function()
  it("accepts a freshly-created unnamed scratch buffer", function()
    local buf = vim.api.nvim_create_buf(false, true)
    assert.is_true(term._buffer_is_empty_scratch(buf))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("rejects a scratch buffer that has content", function()
    local buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "some content" })
    assert.is_false(term._buffer_is_empty_scratch(buf))
    vim.api.nvim_buf_delete(buf, { force = true })
  end)

  it("rejects a named buffer backed by a file", function()
    local tmp = vim.fn.tempname()
    vim.fn.writefile({ "seed" }, tmp)
    vim.cmd("edit " .. tmp)
    local buf = vim.api.nvim_get_current_buf()
    assert.is_false(term._buffer_is_empty_scratch(buf))
    vim.cmd("bwipeout!")
    pcall(os.remove, tmp)
  end)

  it("rejects a modified named buffer even if content is short", function()
    -- A realistic "unsafe" case: user has a real file open with pending
    -- edits. Even a one-line file is not safe to clobber with a terminal.
    local tmp = vim.fn.tempname()
    vim.fn.writefile({ "v1" }, tmp)
    vim.cmd("edit " .. tmp)
    local buf = vim.api.nvim_get_current_buf()
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "v2" })
    assert.is_true(vim.bo[buf].modified, "precondition: buffer should be modified")
    assert.is_false(term._buffer_is_empty_scratch(buf))
    vim.cmd("bwipeout!")
    pcall(os.remove, tmp)
  end)
end)
